name: site
channels:
    - defaults
    - conda-forge
dependencies:
    # base
    - python=3.6.6
    - pip=18.1
    - ipdb=0.11
    # website
    - pelican=3.7.1
    - markdown=2.6.11
    - beautifulsoup4=4.6.3
    - html5lib=1.0.1
    # viz
    - altair=2.2.2
